src/main/java/com/webjaguar/model/Location.java
/* Copyright 2005, 2009 Advanced E-Media Solutions
 *
 */

package com.webjaguar.model;

import java.util.Date;

public class Location {
	
	private Integer id;
	private Integer userId;
	private String name;
	private String keywords = "";
	private String addr1;
	private String addr2;
	private String city;
	private String stateProvince;
	private String zip;
	private String country;
	private String phone;
	private String fax;
	private String htmlCode;
	private Date created;

	public Integer getId()
	{
		return id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public Integer getUserId()
	{
		return userId;
	}

	public void setUserId(Integer userId)
	{
		this.userId = userId;
	}

	public String getName()
	{
		return name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getKeywords()
	{
		return keywords;
	}

	public void setKeywords(String keywords)
	{
		this.keywords = keywords;
	}

	public String getAddr1()
	{
		return addr1;
	}

	public void setAddr1(String addr1)
	{
		this.addr1 = addr1;
	}

	public String getAddr2()
	{
		return addr2;
	}

	public void setAddr2(String addr2)
	{
		this.addr2 = addr2;
	}

	public String getCity()
	{
		return city;
	}

	public void setCity(String city)
	{
		this.city = city;
	}

	public String getStateProvince()
	{
		return stateProvince;
	}

	public void setStateProvince(String stateProvince)
	{
		this.stateProvince = stateProvince;
	}

	public String getZip()
	{
		return zip;
	}

	public void setZip(String zip)
	{
		this.zip = zip;
	}

	public String getCountry()
	{
		return country;
	}

	public void setCountry(String country)
	{
		this.country = country;
	}

	public String getPhone()
	{
		return phone;
	}

	public void setPhone(String phone)
	{
		this.phone = phone;
	}

	public String getFax()
	{
		return fax;
	}

	public void setFax(String fax)
	{
		this.fax = fax;
	}

	public String getHtmlCode()
	{
		return htmlCode;
	}

	public Date getCreated()
	{
		return created;
	}

	public void setCreated(Date created)
	{
		this.created = created;
	}

	public void setHtmlCode(String htmlCode)
	{
		this.htmlCode = htmlCode;
	}

	public String getAddressToString() {
		return this.addr1 + " " + this.addr2 + " " + this.city + " " + this.zip + " " + this.stateProvince + " " + this.country;
	}

}

src/main/java/com/webjaguar/web/admin/location/ImportController.java
/* Copyright 2007 Advanced E-Media Solutions
 * @author Eduardo Asprec
 * @since 03.23.2007
 */

package com.webjaguar.web.admin.location;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.*;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.poi.hssf.usermodel.HSSFCell;
import org.apache.poi.hssf.usermodel.HSSFFormulaEvaluator;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.poifs.filesystem.POIFSFileSystem;
import org.springframework.mail.MailSender;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.context.support.WebApplicationObjectSupport;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.multipart.MultipartHttpServletRequest;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.Controller;

import com.webjaguar.dao.GlobalDao;
import com.webjaguar.logic.WebJaguarFacade;
import com.webjaguar.model.ImportExportHistory;
import com.webjaguar.model.Location;

public class ImportController extends WebApplicationObjectSupport implements Controller {
	
	
	private WebJaguarFacade webJaguar;
	public void setWebJaguar(WebJaguarFacade webJaguar) { this.webJaguar = webJaguar; }
	
    private GlobalDao globalDao;
    public void setGlobalDao(GlobalDao globalDao) { this.globalDao = globalDao; }
	
	private MailSender mailSender;
	public void setMailSender(MailSender mailSender) { this.mailSender = mailSender; }
	
	private HSSFFormulaEvaluator evaluator;
	
	String formView = "admin/location/import";
	
    public ModelAndView handleRequest(HttpServletRequest request, HttpServletResponse response)
		throws Exception {	
        
		File baseFile = new File(getServletContext().getRealPath("/admin/excel/"));
		if (!baseFile.canWrite()){
			return new ModelAndView("admin/location/import", "message", "excelfile.notWritable");	
		}    	
    	
		// check if upload button was pressed
		if (request.getParameter("__upload") != null) {
	    	MultipartHttpServletRequest multipartRequest = (MultipartHttpServletRequest) request;
	    	MultipartFile file = multipartRequest.getFile("file");
	    	if (file != null && !file.isEmpty()) {
	    		File excel_file = new File(baseFile, "locations_import.xls");
	    		file.transferTo(excel_file);
	    		file = null; // delete to save resources
	    		
	    		Map<String, Object> gSiteConfig = (Map<String, Object>) request.getAttribute("gSiteConfig");
	    		List<Location> importedlocations = new ArrayList<Location>();
	        	try {
	                List<Map<String, Object>> addedItems = new ArrayList<Map<String, Object>>();
	                List<Map<String, Object>> updatedItems = new ArrayList<Map<String, Object>>();
	                Map<String, Object> map = new HashMap<String, Object>();
	        		if (processFile(excel_file, gSiteConfig, map, importedlocations, addedItems, updatedItems)) {
	    				this.webJaguar.insertImportExportHistory( new ImportExportHistory("product", SecurityContextHolder.getContext().getAuthentication().getName(), true ));
	    				
	    				for (Location location: importedlocations) {
	        				if(location.getId() == null) {
		        				this.webJaguar.insertLocation(location);
	        				} else {
                				this.webJaguar.updateLocation(location);
                			}        					
	        			}
	        			if (updatedItems.size() > 0) map.put("updatedItems", updatedItems);	    				
	        			if (addedItems.size() > 0) map.put("addedItems", addedItems);	        			
	        			return new ModelAndView("admin/location/importSuccess", map);
	        		} else {
	        			return new ModelAndView(formView, map);
	        		}
	        	} catch (IOException e) {
	    			return new ModelAndView(formView, "message", "excelfile.invalid");
	    		} finally {
	    	    	// delete excel file
	    			excel_file.delete();	    			
	    		} 
	    	} else {
	        	return new ModelAndView(formView, "message", "excelfile.invalid");	    		
	    	}
		}    	
    	return new ModelAndView(formView);
    }
    
    private boolean processFile(File excel_file, Map<String, Object> gSiteConfig, 
    		Map<String, Object> map, List<Location> importedLocations, List<Map<String, Object>> addedItems, List<Map<String, Object>> updatedItems) throws IOException, Exception {
    	
    	
    	List<Map<String, Object>> invalidItems = new ArrayList<Map<String, Object>>();
    	
    	try {
    		
			POIFSFileSystem fs = new POIFSFileSystem(new FileInputStream(excel_file));
			HSSFWorkbook wb = new HSSFWorkbook(fs);
		    
			HSSFSheet sheet = wb.getSheetAt(0); // first sheet
			HSSFRow row     = sheet.getRow(0);  // first row
			
			evaluator = new HSSFFormulaEvaluator(sheet, wb);
			
			Map<String, Short> header = new HashMap<String, Short>();
			Set<String> emails = new HashSet<String>();
			Set<Short> category = new HashSet<Short>();
			
			if (wb.getNumberOfSheets() > 1) {
				// multiple sheets
				map.put("message", "excelfile.multipleSheets");
				return false;					
			}
			if (row == null) {
				// first line should be the headers
				map.put("message", "excelfile.emptyHeaders");
				return false;				
			}
			
		    Iterator iter = row.cellIterator();
		    
		    // get header names
			while (iter.hasNext()) {
				HSSFCell cell = (HSSFCell) iter.next();
				String headerName = "";
				try {
					headerName = cell.getStringCellValue().trim();					
				} catch (NumberFormatException e) {
					// do nothing
				}
				if (!headerName.equals( "" )) {
						if (header.put(headerName.toLowerCase(), cell.getCellNum()) != null) {
							// duplicate header
							map.put("message", "excelfile.duplicateHeaders");
							map.put("arguments", headerName);
							return false;														
					}
				} 
			}
			
			// check required headers
			if (!header.containsKey("address1") || !header.containsKey("city") || !header.containsKey("stateprovince")) { // required fields
				map.put("message", "excelfile.missingHeaders");
				return false;
			} 		
	    	
			
			nextRow: for (int i=1; i<=sheet.getLastRowNum(); i++) {
				row = sheet.getRow(i);
				if (row == null) {
					continue;
				}	
	
				Map<String, Object> thisMap = new HashMap<String, Object>();
				
				//required fields
				String address1 = null;				
				address1 = getStringValue(row, header.get("address1")).trim();
				if(address1 == "") {
					address1 = null;
				}
				String city = null;
				city = getStringValue(row, header.get("city")).trim();
				if(city == "") {
					city = null;
				}
				String stateProvince = null;
				stateProvince = getStringValue(row, header.get("stateprovince")).trim();
				if(stateProvince == "") {
					stateProvince = null;
				}
				
				if(address1 != null && city != null && stateProvince != null) {
					Integer id = null;
					Location location = new Location();
					
					if (header.containsKey("id")) {
						try {
							id = getIntegerValue(row, header.get("id"));
						} catch (Exception e) {
							thisMap.put("id", getStringValue(row, header.get("id")));
							thisMap.put("reason", "Invalid loaction ID");
							invalidItems.add(thisMap);
							continue nextRow;
						}	
						if (id != null && !this.webJaguar.isValidLocationId(id)) { // id not valid
								thisMap.put("id", id);
								thisMap.put("reason", "Invalid location ID");
								invalidItems.add(thisMap);
								continue nextRow;							
						} else {
							processRow(row, header, location);
							thisMap.put("locationname", getStringValue(row, header.get("location")));			
							updatedItems.add(thisMap);
						}
					} else {
						processRow(row, header, location);
						thisMap.put("locationname", getStringValue(row, header.get("location")));			
						addedItems.add(thisMap);
					}		
					importedLocations.add(location);
				}
			}
			
			 if (importedLocations.size() == 0) {	// no locations to import
				map.put("message", "excelfile.empty");
				return false;			
			}		
			return true;
			
        } catch (Exception e) {
        	map.put("message", "excelfile.version");
	    	return false;
        }
	    	  
    }

    private Integer getIntegerValue(HSSFRow row, short cellnum) throws Exception {
		HSSFCell cell = row.getCell(cellnum);
    	Integer value = null;
    	
    	if (cell != null) {
    		switch (cell.getCellType()) {
				case HSSFCell.CELL_TYPE_STRING:
					value = new Integer(cell.getStringCellValue());										
					break;
				case HSSFCell.CELL_TYPE_NUMERIC:
					Double cellValue = cell.getNumericCellValue();
					if (cellValue != cellValue.intValue()) {
						throw new Exception();	
					}
					value =  cellValue.intValue();
					break;
				case HSSFCell.CELL_TYPE_FORMULA:
					evaluator.setCurrentRow(row);
					HSSFFormulaEvaluator.CellValue formulaCellValue = evaluator.evaluate(cell);					
					if (formulaCellValue.getCellType() == HSSFCell.CELL_TYPE_NUMERIC) {
						cellValue =  new Double(formulaCellValue.getNumberValue());
						if (cellValue != cellValue.intValue()) {
							throw new Exception();	
						}
						value =  cellValue.intValue();
					}
					break;
    		} // switch
    	}
    	return value;
    }
    
    private String getStringValue(HSSFRow row, short cellnum) {
		HSSFCell cell = row.getCell(cellnum);
		String value = "";

    	if (cell != null) {
			switch (cell.getCellType()) {
				case HSSFCell.CELL_TYPE_STRING:
					value = cell.getStringCellValue();
					break;
				case HSSFCell.CELL_TYPE_NUMERIC:
					Integer intValue = null;
					try {
						intValue = getIntegerValue(row, cellnum);
					} catch (Exception e) {}
					if (intValue != null) {
						value = intValue.toString();
						break;
					}

src/main/java/com/webjaguar/web/admin/location/LocationFormController.java
/* Copyright 2005, 2007 Advanced E-Media Solutions
 * @author Shahin Naji
 * @since 01.22.2009
 */

package com.webjaguar.web.admin.location;

import java.util.HashMap;
import java.util.Map;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.springframework.validation.BindException;
import org.springframework.validation.Errors;
import org.springframework.validation.ValidationUtils;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.SimpleFormController;
import org.springframework.web.servlet.view.RedirectView;

import com.webjaguar.web.form.LocationForm;
import com.webjaguar.logic.WebJaguarFacade;

public class LocationFormController extends SimpleFormController {
	
	private WebJaguarFacade webJaguar;
	public void setWebJaguar(WebJaguarFacade webJaguar) { this.webJaguar = webJaguar; }

	public LocationFormController() {
		setSessionForm(true);
		setCommandName("locationForm");
		setCommandClass(LocationForm.class);
		setFormView("admin/location/form");
		setSuccessView("locationList.jhtm");
	}
	
	public ModelAndView onSubmit(HttpServletRequest request, HttpServletResponse 
			response, Object command, BindException errors)  throws ServletException {

		LocationForm locationForm = (LocationForm) command;
		
		// check if delete button was pressed
		if (request.getParameter("_delete") != null) {
			this.webJaguar.deleteLocation( locationForm.getLocation().getId() );			
			return new ModelAndView(new RedirectView(getSuccessView()));
		}
		
		if (locationForm.isNewLocation()) {
			this.webJaguar.insertLocation( locationForm.getLocation());
		} else {
			this.webJaguar.updateLocation( locationForm.getLocation());
		}
		
		return new ModelAndView(new RedirectView(getSuccessView()));
	}
	
	protected boolean suppressBinding(HttpServletRequest request) {
		if (request.getParameter("_delete") != null) {
			return true;			
		}
		return false;
	}
	
	protected Object formBackingObject(HttpServletRequest request) 
		throws Exception {
		LocationForm locationForm = new LocationForm();
		if ( request.getParameter("id") != null ) {
			locationForm = new LocationForm(this.webJaguar.getLocationById( new Integer(request.getParameter("id"))), false);
		} else {
			locationForm = new LocationForm();
		}
		
		return locationForm;
	}
	
	protected void onBindAndValidate(HttpServletRequest request, Object command, BindException errors) throws Exception {
		LocationForm locationForm = (LocationForm) command;
		ValidationUtils.rejectIfEmptyOrWhitespace(errors, "location.addr1", "form.required", "Address 1 is required.");    	
		ValidationUtils.rejectIfEmptyOrWhitespace(errors, "location.city", "form.required", "City is required.");  
		if (locationForm.getLocation().getCountry().equalsIgnoreCase("US") || locationForm.getLocation().getCountry().equalsIgnoreCase("CA")) {
			ValidationUtils.rejectIfEmptyOrWhitespace(errors, "location.stateProvince", "form.required", "State is required.");
		}
	}
	
    protected Map referenceData(HttpServletRequest request, Object command, Errors errors) throws Exception {
    	LocationForm locationForm = (LocationForm) command;

    	Map<String, Object> map = new HashMap<String, Object>();
		map.put("countries",this.webJaguar.getEnabledCountryList());
		map.put("states",this.webJaguar.getStateList("US"));
		map.put("caProvinceList", this.webJaguar.getStateList("CA"));
		return map;
    }
}

src/main/java/com/webjaguar/web/frontend/account/AddToListController.java
/* Copyright 2005, 2006 Advanced E-Media Solutions
 *
 */

package com.webjaguar.web.frontend.account;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.Controller;
import org.springframework.web.servlet.view.RedirectView;
import org.springframework.web.util.WebUtils;

import com.webjaguar.logic.WebJaguarFacade;
import com.webjaguar.model.Cart;
import com.webjaguar.model.CartItem;
import com.webjaguar.model.Layout;
import com.webjaguar.model.UserSession;

public class AddToListController implements Controller {

	private WebJaguarFacade webJaguar;
	
    public ModelAndView handleRequest(HttpServletRequest request, HttpServletResponse response)
		throws Exception {

    	UserSession userSession = this.webJaguar.getUserSession(request);
    	String ids[] = request.getParameterValues("product.id");
    	if (ids != null) {
    		this.webJaguar.addToList(ids, userSession.getUserid());
    	}
    	
		Layout layout = (Layout) request.getAttribute("layout");
		this.webJaguar.updateCartQuantity(userSession, request, layout);
		layout.setTopBarHtml(layout.getTopBarHtml().replaceAll("#pageName#", "Edit Information"));

		return new ModelAndView(new RedirectView("viewList.jhtm"));
	}
    
	public void setWebJaguar(WebJaguarFacade webJaguar) {
		this.webJaguar = webJaguar;
	}

}

src/main/webapp/WEB-INF/jsp/frontend/account/location/locationForm.jsp
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>

<tiles:insertDefinition name="${_template}" flush="true">
  <tiles:putAttribute name="content" type="string">

<c:if test="${gSiteConfig['gLOCATION']}"> 

<script language="JavaScript">
<!--

//-->
</script>

<form:form  commandName="locationForm" method="post">
<table border="0" cellpadding="3" cellspacing="1" width="100%">
  <tr>
    <td class="formNameReq"><fmt:message key="keywords" />:</td>
    <td>
      <form:textarea path="location.keywords" rows="10" cols="40" cssClass="textfield" htmlEscape="true"/>
      <form:errors path="location.keywords" cssClass="error" />
    </td>
  </tr>
</table>  

<div align="center">
  <input type="submit" value="<fmt:message key="update" />">
  <input type="submit" value="<fmt:message key="cancel" />" name="_cancel">
</div>
</form:form>

</c:if>
  </tiles:putAttribute>
</tiles:insertDefinition>

src/main/webapp/WEB-INF/jsp/frontend/account/location/locationWishList.jsp
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>

<tiles:insertDefinition name="${_template}" flush="true">
  <tiles:putAttribute name="content" type="string">

<c:if test="${gSiteConfig['gLOCATION']}"> 

<c:if test="${model.locationWishList.nrOfElements > 0}">
<script language="JavaScript">
<!--
function toggleAll(el) {
	var ids = document.getElementsByName("__selected_id");	
  	if (ids.length == 1)
      document.mylist.__selected_id.checked = el.checked;
    else
      for (i = 0; i < ids.length; i++)
        document.mylist.__selected_id[i].checked = el.checked;	
}  

function deleteSelected() {
	var ids = document.getElementsByName("__selected_id");	
  	if (ids.length == 1) {
      if (document.mylist.__selected_id.checked) {
    	return confirm('Delete permanently?');
      }
    } else {
      for (i = 0; i < ids.length; i++) {
        if (document.mylist.__selected_id[i].checked) {
    	  return confirm('Delete permanently?');
        }
      }
    }

    alert("Please select to delete.");       
    return false;
}
//-->
</script>
</c:if>
<form name="mylist" method="post">
<table width="90%" align="center" cellspacing="5" cellpadding="0" border="0">
  <tr>
	<td>&nbsp;</td>
	<td>
<div class="pageNavi">Page 
		<select name="page" onchange="submit()">
		<c:forEach begin="1" end="${model.locationWishList.pageCount}" var="page">
  	        <option value="${page}" <c:if test="${page == (model.locationWishList.page+1)}">selected</c:if>>${page}</option>
		</c:forEach>
		</select>
of <c:out value="${model.locationWishList.pageCount}"/></div>
	</td>
  </tr>
  <tr>
	<td colspan="2">
<table border="0" cellpadding="3" cellspacing="1" width="100%" class="listings"> 
  <tr class="listingsHdr2">
  <c:set var="cols" value="0"/>
<c:if test="${model.locationWishList.nrOfElements > 0}">
	<c:set var="cols" value="${cols+1}"/>
    <td align="center"><input type="checkbox" onclick="toggleAll(this)"></td>
</c:if>
    <td class="nameCol">Name</td>
    <td class="nameCol">Address</td>
    <td class="nameCol" style="white-space: nowrap">Added</td>
  </tr>
<c:forEach items="${model.locationWishList.pageList}" var="location" varStatus="status">
  <tr class="row${status.index % 2}">
<c:if test="${model.locationWishList.nrOfElements > 0}">
    <td align="center"><input name="__selected_id" value="${location.id}" type="checkbox"></td>
</c:if>
    <td class="nameCol"><c:out value="${location.name}" /></td>
	<td class="nameCol"><c:out value="${location.addressToString}"/></td>			
    <td class="nameCol" style="white-space: nowrap"><fmt:formatDate type="date" timeStyle="default" value="${location.created}"/></td>	
  </tr>
</c:forEach>
<c:choose>
 <c:when test="${model.locationWishList.nrOfElements == 0}">
   <tr class="emptyList"><td colspan="${3+cols}">&nbsp;</td></tr>
 </c:when>
</c:choose>
</table>
	</td>
  </tr>
<c:if test="${model.locationWishList.nrOfElements > 0}">
  <tr>
	<td><input type="submit" name="__delete" value="Delete Selected." onClick="return deleteSelected()"></td>
  </tr>
</c:if>
</table>
</form>

</c:if>

  </tiles:putAttribute>
</tiles:insertDefinition>